server:
  port: 8080

#logging:
#  level:
#    root: debug
##    org.springframwwork.web: debug
##    org.hibernate.SQL: debug

spring:
  datasource:
    url: 'jdbc:h2:mem:library'
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: '/h2-console'
